### PR TITLE
Update index.html title to ESS SchulichHub

### PR DESCRIPTION
**Pull request by lemohammed**

### CODE REVIEW

**Review by RatikKapoor — APPROVED** [review]
🚢, @lemohammed I'm assuming we'll update the Ionic favicon after Ana and Aamna create a logo?

**Comment by lemohammed** [comment]
Yup, we can add that as a new issue :)

**Comment by lemohammed** [comment]
Ohh haha I just read the little comment you wrote there. Wanna stick to adding a new issue ?

**Review by rjb75 — APPROVED** [review]
👏👏

**Review by RatikKapoor — APPROVED** [review]
🚀

**Pull request merged**
